sudo: required
services: 
   - docker

before_install:
   - docker build -t keithraker/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true keithraker/docker-react npm run test -- --coverage
